
modLoader = "javafml"
loaderVersion = "[42,)"
license = "All Rights Reserved"

[[mods]]
modId = "simplicity"
version = "${file.jarVersion}"
displayName = "Simplicity"
description = '''

'''

[[dependencies.simplicity]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplicity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,1.20)"
ordering = "NONE"
side = "BOTH"
